dataset:
    dataset_path: "data"
    dataset_name: "pascal-part"   
image:
    base_size: 512
    crop_size: 512
network:
    backbone: "resnet50"  #choices=['resnet50', 'resnet101', 'mobilenet']
    num_mask_levels: 3
    num_classes_level_0: 2
    num_classes_level_1: 3
    num_classes_level_2: 7
training:
    workers: 8
    loss_type: "ce"   #choices=['ce', 'focal']
    epochs: 100
    start_epoch: 0
    batch_size: 4
    lr: 0.0005
    lr_scheduler: "poly"     #choices=['poly', 'step', 'cos']
    lr_step: 0
    warmup_epochs: 0
    momentum: 0.9
    weight_decay: 0.0005
    callbacks:
    weights_initialization: 
        # use_pretrained_weights: true
        # restore_from: "./experiments/checkpoint_last.pth.tar"
    model_best_checkpoint: 
        enabled: true
        out_file: "./experiments/checkpoint_best.pth.tar"
        monitor: "val_loss"
    model_last_checkpoint: 
        enabled: true
        out_file: "./experiments/checkpoint_last.pth.tar"        
    output:
        output_weights: "./snapshots/checkpoint_best.pth.tar"
    tensorboard: 
        enabled: true
        log_dir: "./tensorboard/"
    # no_val: false
    val_interval: 1
inference:
    batch_size: 4
#gpu_ids: 0
#seed: 1
#ft: false
#no_val: false